version: '3.4'
networks: { intr: { external: true } }
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "100k"
    max-file: "3"
volumes:
  wp_db_data: { driver: "local" }
services:

  wp:
    image: wordpress
    logging: *default-logging
    networks: [ "intr" ]
    volumes:
    - ./www:/var/www/html
    environment:
      WORDPRESS_DB_HOST: wp_db:3306
      WORDPRESS_DB_PASSWORD: wordpress
    ports: [ 8001:80 ]

  wp_db:
    image: mysql:5.7
    logging: *default-logging
    networks: [ "intr" ]
    volumes:
     - wp_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress